[package]
name = "openmicrod"
version = "0.1.0"
edition.workspace = true

[dependencies]
openmicro-proto = { path = "../openmicro-proto", features = ["std"] }
serde = { workspace = true, features = ["std"] }
serde_json.workspace = true
toml.workspace = true
tokio.workspace = true
anyhow.workspace = true
async-trait.workspace = true
